add isActive

diff --git a/ldto b/ldto
--- a/ldto
+++ b/ldto
@@ -5,13 +5,13 @@
 # PURPOSE: Manage the application and removal of device tree overlays in the Linux kernel.
 
 if [ "$USER" != "root" ]; then
-	echo "Please run this as root or with sudo privileges."
+	echo "Please run this as root." >&2
 	exit 1
 fi
 
 if [ -z "$VENDOR" ]; then
 	if [ ! -e /sys/class/dmi/id/board_vendor ]; then
-		echo "No vendor found!"
+		echo "No vendor found!" >&2
 		exit 1
 	fi
 	VENDOR=$(tr -d '\0' < /sys/class/dmi/id/board_vendor)
@@ -20,7 +20,7 @@ fi
 
 if [ -z "$BOARD" ]; then
 	if [ ! -e /sys/class/dmi/id/board_name ]; then
-		echo "No boardname found!"
+		echo "No boardname found!" >&2
 		exit 1
 	fi
 	BOARD=$(tr -d '\0' < /sys/class/dmi/id/board_name)
@@ -38,16 +38,16 @@ LDTO_enableOverlay()
 	fi
 	DTBO="$FIRMWARE/$1.dtbo"
 	if [ ! -f $DTBO ]; then
-		echo "Overlay $1: does not exist and cannot be added"
+		echo "Overlay $1: does not exist and cannot be added" >&2
 		return 1
 	fi
 	if [ -e $OVERLAYS/$1 ]; then
-		echo "Overlay $1: already exists"
+		echo "Overlay $1: already exists" >&2
 		return 1
 	fi
 	mkdir $OVERLAYS/$1
 	cat $FIRMWARE/$1.dtbo > $OVERLAYS/$1/dtbo
-	echo "Overlay $1: `cat $OVERLAYS/$1/status`"
+	echo "Overlay $1: `cat $OVERLAYS/$1/status`" >&2
 }
 
 LDTO_disableOverlay()
@@ -57,16 +57,16 @@ LDTO_disableOverlay()
 		return 1
 	fi
 	if [ ! -e "$OVERLAYS/$1" ]; then
-		echo "Overlay $1: does not exist and cannot be removed"
+		echo "Overlay $1: does not exist and cannot be removed" >&2
 		return 1
 	fi
 	rmdir $OVERLAYS/$1
-	echo "Overlay $1: removed"
+	echo "Overlay $1: removed" >&2
 }
 
-listActiveOverlays()
+LDTO_listActiveOverlays()
 {
-	echo "Active Overlays:"
+	echo "#Active Overlays:" >&2
 	for i in `ls $OVERLAYS`;
 	do
 		basename $i
@@ -74,13 +74,26 @@ listActiveOverlays()
 }
 LDTO_listOverlays()
 {
-	listActiveOverlays
+	LDTO_listActiveOverlays
 
-	echo "Available Overlays:"
+	echo "#Available Overlays:" >&2
 	for i in $FIRMWARE/*.dtbo
 	do
 		basename $i .dtbo
 	done
+}
+LDTO_isActiveOverlay()
+{
+	if [ -z "$1" ]; then
+		return 1
+	fi
+	for i in `ls $OVERLAYS`;
+	do
+		if [ "$1" = $(basename $i) ]; then
+			return 0
+		fi
+	done
+	return 1
 }
 
 LDTO_showHelp()
@@ -100,11 +113,17 @@ case "$1" in
 		;;
 	list)
 		cmd=LDTO_listOverlays
-	;;
+		;;
+	listActive)
+		cmd=LDTO_listActiveOverlays
+		;;
+	isActive)
+		cmd=LDTO_isActiveOverlay
+		;;
 	*)
 		$cmd
 		exit 1
-	;;
+		;;
 esac
 shift
 $cmd $@
