ldto: support aliases for enable and disable

diff --git a/ldto b/ldto
--- a/ldto
+++ b/ldto
@@ -69,17 +69,9 @@ LDTO_getAliasDT()
 
 LDTO_getDTBO()
 {
-	local dtbo="$PATH_DTBO/$1.dtbo"
-	if [ -f "$dtbo" ]; then
-		echo "$dtbo"
-	else
-		local dt=$(LDTO_getAliasDT "$1")
-		if [ ! -z "$dt" ]; then
-			local dtbo="$PATH_DTBO/$dt.dtbo"
-			if [ -f "$dtbo" ]; then
-				echo "$dtbo"
-			fi
-		fi
+	local dtbo_file="$PATH_DTBO/$1.dtbo"
+	if [ -f "$dtbo_file" ]; then
+		echo "$dtbo_file"
 	fi
 }
 
@@ -94,8 +86,8 @@ LDTO_list()
 	echo "#Overlays available" >&2
 	for i in $dtbos
 	do
-		local dt=$(basename $i .dtbo)
-		echo "$dt	$(LDTO_getDTAlias $dt)"
+		local dto=$(basename $i .dtbo)
+		echo "$dto	$(LDTO_getDTAlias $dto)"
 	done
 }
 
@@ -122,19 +114,23 @@ LDTO_enable()
 	fi
 	LDTO_checkOFConfig RW
 	LDTO_loadMap
-	for dtbo in "$@"; do
-		local dtbo_file=$(LDTO_getDTBO "$dtbo")
+	for dto in "$@"; do
+		local dto_real=$(LDTO_getAliasDT "$dto")
+		if [ ! -z "$dto_real" ]; then
+			local dto=$dto_real
+		fi
+		local dtbo_file=$(LDTO_getDTBO "$dto")
 		if [ -z "$dtbo_file" ]; then
-			echo "$FUNCNAME: $dtbo does not exist and cannot be added" >&2
+			echo "$FUNCNAME: $dto does not exist and cannot be added" >&2
 			return 1
 		fi
-		if [ -e "$PATH_OF_CONFIG/$dtbo" ]; then
-			echo "Overlay $dtbo: already exists" >&2
+		if [ -e "$PATH_OF_CONFIG/$dto" ]; then
+			echo "Overlay $dto: already exists" >&2
 			return 1
 		fi
-		mkdir "$PATH_OF_CONFIG/$dtbo"
-		cat "$dtbo_file" > "$PATH_OF_CONFIG/$dtbo/dtbo"
-		echo "Overlay $dtbo: `cat $PATH_OF_CONFIG/$dtbo/status`" >&2
+		mkdir "$PATH_OF_CONFIG/$dto"
+		cat "$dtbo_file" > "$PATH_OF_CONFIG/$dto/dtbo"
+		echo "Overlay $dto: `cat $PATH_OF_CONFIG/$dto/status`" >&2
 	done
 }
 
@@ -146,18 +142,17 @@ LDTO_disable()
 	fi
 	LDTO_checkOFConfig RW
 	LDTO_loadMap
-	for dtbo in "$@"; do
-		if [ ! -e "$PATH_OF_CONFIG/$dtbo" ]; then
-			local dt=$(LDTO_getAliasDT "$dtbo")
-			if [ ! -z "$dt" ]; then
-				rmdir $PATH_OF_CONFIG/$dt
-				echo "Overlay $dt: removed" >&2
-			fi
-			echo "Overlay $dtbo: does not exist and cannot be removed" >&2
+	for dto in "$@"; do
+		local dto_real=$(LDTO_getAliasDT "$dto")
+		if [ ! -z "$dto_real" ]; then
+			local dto=$dto_real
+		fi
+		if [ ! -e "$PATH_OF_CONFIG/$dto" ]; then
+			echo "Overlay $dto: does not exist and cannot be removed" >&2
 			return 1
 		fi
-		rmdir $PATH_OF_CONFIG/$dtbo
-		echo "Overlay $dtbo: removed" >&2
+		rmdir $PATH_OF_CONFIG/$dto
+		echo "Overlay $dto: removed" >&2
 	done
 }
 
@@ -276,14 +271,18 @@ LDTO_merge()
 		return 1
 	fi
 	LDTO_loadMap
-	for dtbo in "$@"; do
-		local dtbo_file=$(LDTO_getDTBO "$dtbo")
+	for dto in "$@"; do
+		local dto_real=$(LDTO_getAliasDT "$dto")
+		if [ ! -z "$dto_real" ]; then
+			local dto=$dto_real
+		fi
+		local dtbo_file=$(LDTO_getDTBO "$dto")
 		if [ -z "$dtbo_file" ]; then
-			echo "$FUNCNAME: $dtbo does not exist and cannot be added." >&2
+			echo "$FUNCNAME: $dto does not exist and cannot be added." >&2
 			return 1
 		fi
 		LDTO_apply "$dtbo_file"
-		echo "Overlay $dtbo: merged for next boot" >&2
+		echo "Overlay $dto: merged for next boot" >&2
 	done
 }
 
