ldto: merge enable multiple

diff --git a/ldto b/ldto
--- a/ldto
+++ b/ldto
@@ -203,13 +203,15 @@ LDTO_merge()
 		LDTO_list
 		return 1
 	fi
-	DTBO="$PATH_DTBO/$1.dtbo"
-	if [ ! -f "$DTBO" ]; then
-		echo "$FUNCNAME: $1 does not exist and cannot be added." >&2
-		return 1
-	fi
-	LDTO_apply "$DTBO"
-	echo "Overlay $1: merged for next boot" >&2
+	for dtbo in "$@"; do
+		DTBO="$PATH_DTBO/$dtbo.dtbo"
+		if [ ! -f "$DTBO" ]; then
+			echo "$FUNCNAME: $dtbo does not exist and cannot be added." >&2
+			return 1
+		fi
+		LDTO_apply "$DTBO"
+		echo "Overlay $dtbo: merged for next boot" >&2
+	done
 }
 
 LDTO_checkOverrideDT()
